// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.6
// source: cloud/pubsub/v1/data.proto

package pubsubdata

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The event data when a message is published to a topic.
type MessagePublishedData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The message that was published.
	Message *PubsubMessage `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// The resource name of the subscription for which this event was
	// generated. The format of the value is
	// `projects/{project-id}/subscriptions/{subscription-id}`.
	Subscription string `protobuf:"bytes,2,opt,name=subscription,proto3" json:"subscription,omitempty"`
	// The approximate number of times that Pub/Sub has attempted to deliver
	// the associated message to a subscriber.
	//
	// More precisely, this is 1 + (number of NACKs) +
	// (number of ack_deadline exceeds) for this message.
	//
	// Upon the first delivery of a given message, `delivery_attempt` will have a
	// value of 1. The value is calculated at best effort and is approximate.
	//
	// If a DeadLetterPolicy is not set on the subscription, this will be 0.
	DeliveryAttempt int32 `protobuf:"varint,3,opt,name=delivery_attempt,json=deliveryAttempt,proto3" json:"delivery_attempt,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MessagePublishedData) Reset() {
	*x = MessagePublishedData{}
	mi := &file_cloud_pubsub_v1_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagePublishedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagePublishedData) ProtoMessage() {}

func (x *MessagePublishedData) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_pubsub_v1_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagePublishedData.ProtoReflect.Descriptor instead.
func (*MessagePublishedData) Descriptor() ([]byte, []int) {
	return file_cloud_pubsub_v1_data_proto_rawDescGZIP(), []int{0}
}

func (x *MessagePublishedData) GetMessage() *PubsubMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *MessagePublishedData) GetSubscription() string {
	if x != nil {
		return x.Subscription
	}
	return ""
}

func (x *MessagePublishedData) GetDeliveryAttempt() int32 {
	if x != nil {
		return x.DeliveryAttempt
	}
	return 0
}

// A message published to a topic.
type PubsubMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The binary data in the message.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Attributes for this message.
	Attributes map[string]string `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// ID of this message, assigned by the server when the message is published.
	// Guaranteed to be unique within the topic.
	MessageId string `protobuf:"bytes,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// The time at which the message was published, populated by the server when
	// it receives the `Publish` call.
	PublishTime *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=publish_time,json=publishTime,proto3" json:"publish_time,omitempty"`
	// If non-empty, identifies related messages for which publish order should be
	// respected.
	OrderingKey   string `protobuf:"bytes,5,opt,name=ordering_key,json=orderingKey,proto3" json:"ordering_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PubsubMessage) Reset() {
	*x = PubsubMessage{}
	mi := &file_cloud_pubsub_v1_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PubsubMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubsubMessage) ProtoMessage() {}

func (x *PubsubMessage) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_pubsub_v1_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubsubMessage.ProtoReflect.Descriptor instead.
func (*PubsubMessage) Descriptor() ([]byte, []int) {
	return file_cloud_pubsub_v1_data_proto_rawDescGZIP(), []int{1}
}

func (x *PubsubMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PubsubMessage) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *PubsubMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *PubsubMessage) GetPublishTime() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishTime
	}
	return nil
}

func (x *PubsubMessage) GetOrderingKey() string {
	if x != nil {
		return x.OrderingKey
	}
	return ""
}

var File_cloud_pubsub_v1_data_proto protoreflect.FileDescriptor

const file_cloud_pubsub_v1_data_proto_rawDesc = "" +
	"\n" +
	"\x1acloud/pubsub/v1/data.proto\x12\x1dgoogle.events.cloud.pubsub.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xad\x01\n" +
	"\x14MessagePublishedData\x12F\n" +
	"\amessage\x18\x01 \x01(\v2,.google.events.cloud.pubsub.v1.PubsubMessageR\amessage\x12\"\n" +
	"\fsubscription\x18\x02 \x01(\tR\fsubscription\x12)\n" +
	"\x10delivery_attempt\x18\x03 \x01(\x05R\x0fdeliveryAttempt\"\xc1\x02\n" +
	"\rPubsubMessage\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\\\n" +
	"\n" +
	"attributes\x18\x02 \x03(\v2<.google.events.cloud.pubsub.v1.PubsubMessage.AttributesEntryR\n" +
	"attributes\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\tR\tmessageId\x12=\n" +
	"\fpublish_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vpublishTime\x12!\n" +
	"\fordering_key\x18\x05 \x01(\tR\vorderingKey\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01Bm\xaa\x02&Google.Events.Protobuf.Cloud.PubSub.V1\xca\x02\x1dGoogle\\Events\\Cloud\\PubSub\\V1\xea\x02!Google::Events::Cloud::PubSub::V1b\x06proto3"

var (
	file_cloud_pubsub_v1_data_proto_rawDescOnce sync.Once
	file_cloud_pubsub_v1_data_proto_rawDescData []byte
)

func file_cloud_pubsub_v1_data_proto_rawDescGZIP() []byte {
	file_cloud_pubsub_v1_data_proto_rawDescOnce.Do(func() {
		file_cloud_pubsub_v1_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cloud_pubsub_v1_data_proto_rawDesc), len(file_cloud_pubsub_v1_data_proto_rawDesc)))
	})
	return file_cloud_pubsub_v1_data_proto_rawDescData
}

var file_cloud_pubsub_v1_data_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cloud_pubsub_v1_data_proto_goTypes = []any{
	(*MessagePublishedData)(nil),  // 0: google.events.cloud.pubsub.v1.MessagePublishedData
	(*PubsubMessage)(nil),         // 1: google.events.cloud.pubsub.v1.PubsubMessage
	nil,                           // 2: google.events.cloud.pubsub.v1.PubsubMessage.AttributesEntry
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_cloud_pubsub_v1_data_proto_depIdxs = []int32{
	1, // 0: google.events.cloud.pubsub.v1.MessagePublishedData.message:type_name -> google.events.cloud.pubsub.v1.PubsubMessage
	2, // 1: google.events.cloud.pubsub.v1.PubsubMessage.attributes:type_name -> google.events.cloud.pubsub.v1.PubsubMessage.AttributesEntry
	3, // 2: google.events.cloud.pubsub.v1.PubsubMessage.publish_time:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cloud_pubsub_v1_data_proto_init() }
func file_cloud_pubsub_v1_data_proto_init() {
	if File_cloud_pubsub_v1_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cloud_pubsub_v1_data_proto_rawDesc), len(file_cloud_pubsub_v1_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cloud_pubsub_v1_data_proto_goTypes,
		DependencyIndexes: file_cloud_pubsub_v1_data_proto_depIdxs,
		MessageInfos:      file_cloud_pubsub_v1_data_proto_msgTypes,
	}.Build()
	File_cloud_pubsub_v1_data_proto = out.File
	file_cloud_pubsub_v1_data_proto_goTypes = nil
	file_cloud_pubsub_v1_data_proto_depIdxs = nil
}
