name: Generate Library (Fork)

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      LIBRARY_CHECKOUT_PATH: library
      DATA_SOURCE_CHECKOUT_PATH: protos-source-repo

    steps:
    - name: Go Library > Checkout Repository
      uses: actions/checkout@v4
      with:
        path: ${{ env.LIBRARY_CHECKOUT_PATH }}

    - name: Proto Schemas > Checkout Repository
      uses: actions/checkout@v4
      with:
        repository: googleapis/google-cloudevents
        path: ${{ env.DATA_SOURCE_CHECKOUT_PATH }}

    - name: Set Environment
      run: echo "GENERATE_DATA_SOURCE=${PWD}/${DATA_SOURCE_CHECKOUT_PATH}" | tee -a $GITHUB_ENV

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.x

    - name: Install the generator
      run: bash tools/setup-generator.sh
      working-directory: ${{ env.LIBRARY_CHECKOUT_PATH }}

    - name: Run the generator
      run: bash ./generate-code.sh
      working-directory: ${{ env.LIBRARY_CHECKOUT_PATH }}
      env:
        GENERATE_PROTOC_PATH: tmp/protobuf/bin/protoc
        GOFLAGS: "-v"

    - name: View generator output
      if: ${{ failure() }}
      working-directory: ${{ env.LIBRARY_CHECKOUT_PATH }}
      run: |
        git add -N .
        git diff

    - name: Commit and push generated code
      working-directory: ${{ env.LIBRARY_CHECKOUT_PATH }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -B generator
        git add -A
        git diff --cached --quiet && echo "No changes to commit" && exit 0
        git commit -m "feat: Run the code generator (include pubsub)"
        git push -f origin generator
